#ifdef __CLING__
#pragma cling optimize(0)
#endif
void KE()
{
//=========Macro generated from canvas: c/Stacked Histograms
//=========  (Wed Dec  4 23:56:27 2024) by ROOT version 6.28/12
   TCanvas *c = new TCanvas("c", "Stacked Histograms",0,0,800,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-375,-3504.044,2125,21524.84);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.15);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.14);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("Stacked Histograms;Kinetic Energy (MeV);Events");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","Stacked Histograms",50,0,2000);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(20273.4);
   hs_stack_1->SetDirectory(nullptr);
   hs_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->SetLineWidth(0);
   hs_stack_1->GetXaxis()->SetTitle("Kinetic Energy (MeV)");
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.04);
   hs_stack_1->GetXaxis()->SetTitleSize(0.06);
   hs_stack_1->GetXaxis()->SetTickLength(0.02);
   hs_stack_1->GetXaxis()->SetTitleOffset(1);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetTitle("Events");
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.04);
   hs_stack_1->GetYaxis()->SetTitleSize(0.06);
   hs_stack_1->GetYaxis()->SetTickLength(0.01);
   hs_stack_1->GetYaxis()->SetTitleOffset(0.9);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.04);
   hs_stack_1->GetZaxis()->SetTitleSize(0.06);
   hs_stack_1->GetZaxis()->SetTitleOffset(1);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *hist_fate_NC_stack_1 = new TH1D("hist_fate_NC_stack_1","KE - No Interaction (NS)",50,0,2000);
   hist_fate_NC_stack_1->SetBinContent(0,2480);
   hist_fate_NC_stack_1->SetBinContent(1,817);
   hist_fate_NC_stack_1->SetBinContent(2,745);
   hist_fate_NC_stack_1->SetBinContent(3,948);
   hist_fate_NC_stack_1->SetBinContent(4,1966);
   hist_fate_NC_stack_1->SetBinContent(5,2527);
   hist_fate_NC_stack_1->SetBinContent(6,2239);
   hist_fate_NC_stack_1->SetBinContent(7,2487);
   hist_fate_NC_stack_1->SetBinContent(8,2522);
   hist_fate_NC_stack_1->SetBinContent(9,2560);
   hist_fate_NC_stack_1->SetBinContent(10,2858);
   hist_fate_NC_stack_1->SetBinContent(11,3001);
   hist_fate_NC_stack_1->SetBinContent(12,3001);
   hist_fate_NC_stack_1->SetBinContent(13,3096);
   hist_fate_NC_stack_1->SetBinContent(14,3259);
   hist_fate_NC_stack_1->SetBinContent(15,2991);
   hist_fate_NC_stack_1->SetBinContent(16,3032);
   hist_fate_NC_stack_1->SetBinContent(17,2853);
   hist_fate_NC_stack_1->SetBinContent(18,2732);
   hist_fate_NC_stack_1->SetBinContent(19,2475);
   hist_fate_NC_stack_1->SetBinContent(20,2425);
   hist_fate_NC_stack_1->SetBinContent(21,2405);
   hist_fate_NC_stack_1->SetBinContent(22,2317);
   hist_fate_NC_stack_1->SetBinContent(23,2080);
   hist_fate_NC_stack_1->SetBinContent(24,1939);
   hist_fate_NC_stack_1->SetBinContent(25,1798);
   hist_fate_NC_stack_1->SetBinContent(26,1849);
   hist_fate_NC_stack_1->SetBinContent(27,1827);
   hist_fate_NC_stack_1->SetBinContent(28,1816);
   hist_fate_NC_stack_1->SetBinContent(29,1999);
   hist_fate_NC_stack_1->SetBinContent(30,1871);
   hist_fate_NC_stack_1->SetBinContent(31,1859);
   hist_fate_NC_stack_1->SetBinContent(32,1672);
   hist_fate_NC_stack_1->SetBinContent(33,1750);
   hist_fate_NC_stack_1->SetBinContent(34,1556);
   hist_fate_NC_stack_1->SetBinContent(35,1492);
   hist_fate_NC_stack_1->SetBinContent(36,1635);
   hist_fate_NC_stack_1->SetBinContent(37,1466);
   hist_fate_NC_stack_1->SetBinContent(38,1422);
   hist_fate_NC_stack_1->SetBinContent(39,1396);
   hist_fate_NC_stack_1->SetBinContent(40,1462);
   hist_fate_NC_stack_1->SetBinContent(41,1368);
   hist_fate_NC_stack_1->SetBinContent(42,1260);
   hist_fate_NC_stack_1->SetBinContent(43,1266);
   hist_fate_NC_stack_1->SetBinContent(44,1128);
   hist_fate_NC_stack_1->SetBinContent(45,1144);
   hist_fate_NC_stack_1->SetBinContent(46,1014);
   hist_fate_NC_stack_1->SetBinContent(47,1059);
   hist_fate_NC_stack_1->SetBinContent(48,1016);
   hist_fate_NC_stack_1->SetBinContent(49,1017);
   hist_fate_NC_stack_1->SetBinContent(50,956);
   hist_fate_NC_stack_1->SetBinContent(51,30131);
   hist_fate_NC_stack_1->SetEntries(127984);
   hist_fate_NC_stack_1->SetDirectory(nullptr);

   ci = TColor::GetColor("#ff0000");
   hist_fate_NC_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   hist_fate_NC_stack_1->SetLineColor(ci);
   hist_fate_NC_stack_1->GetXaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetXaxis()->SetTitleOffset(1);
   hist_fate_NC_stack_1->GetXaxis()->SetTitleFont(42);
   hist_fate_NC_stack_1->GetYaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetYaxis()->SetTitleFont(42);
   hist_fate_NC_stack_1->GetZaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetZaxis()->SetTitleOffset(1);
   hist_fate_NC_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_NC_stack_1,"");
   
   TH1D *hist_fate_ChEx_stack_2 = new TH1D("hist_fate_ChEx_stack_2","KE - No ChEx (ChEx)",50,0,2000);
   hist_fate_ChEx_stack_2->SetBinContent(0,1863);
   hist_fate_ChEx_stack_2->SetBinContent(1,279);
   hist_fate_ChEx_stack_2->SetBinContent(2,303);
   hist_fate_ChEx_stack_2->SetBinContent(3,324);
   hist_fate_ChEx_stack_2->SetBinContent(4,337);
   hist_fate_ChEx_stack_2->SetBinContent(5,528);
   hist_fate_ChEx_stack_2->SetBinContent(6,624);
   hist_fate_ChEx_stack_2->SetBinContent(7,666);
   hist_fate_ChEx_stack_2->SetBinContent(8,569);
   hist_fate_ChEx_stack_2->SetBinContent(9,590);
   hist_fate_ChEx_stack_2->SetBinContent(10,408);
   hist_fate_ChEx_stack_2->SetBinContent(11,350);
   hist_fate_ChEx_stack_2->SetBinContent(12,425);
   hist_fate_ChEx_stack_2->SetBinContent(13,259);
   hist_fate_ChEx_stack_2->SetBinContent(14,93);
   hist_fate_ChEx_stack_2->SetBinContent(15,40);
   hist_fate_ChEx_stack_2->SetBinContent(16,78);
   hist_fate_ChEx_stack_2->SetBinContent(17,66);
   hist_fate_ChEx_stack_2->SetBinContent(18,73);
   hist_fate_ChEx_stack_2->SetBinContent(19,60);
   hist_fate_ChEx_stack_2->SetBinContent(20,44);
   hist_fate_ChEx_stack_2->SetBinContent(21,18);
   hist_fate_ChEx_stack_2->SetBinContent(22,32);
   hist_fate_ChEx_stack_2->SetBinContent(23,25);
   hist_fate_ChEx_stack_2->SetBinContent(24,23);
   hist_fate_ChEx_stack_2->SetBinContent(25,28);
   hist_fate_ChEx_stack_2->SetBinContent(26,23);
   hist_fate_ChEx_stack_2->SetBinContent(27,13);
   hist_fate_ChEx_stack_2->SetBinContent(28,24);
   hist_fate_ChEx_stack_2->SetBinContent(29,3);
   hist_fate_ChEx_stack_2->SetBinContent(30,21);
   hist_fate_ChEx_stack_2->SetBinContent(31,13);
   hist_fate_ChEx_stack_2->SetBinContent(32,6);
   hist_fate_ChEx_stack_2->SetBinContent(33,15);
   hist_fate_ChEx_stack_2->SetBinContent(34,10);
   hist_fate_ChEx_stack_2->SetBinContent(35,3);
   hist_fate_ChEx_stack_2->SetBinContent(36,6);
   hist_fate_ChEx_stack_2->SetBinContent(37,3);
   hist_fate_ChEx_stack_2->SetBinContent(38,2);
   hist_fate_ChEx_stack_2->SetBinContent(39,10);
   hist_fate_ChEx_stack_2->SetBinContent(40,15);
   hist_fate_ChEx_stack_2->SetBinContent(41,2);
   hist_fate_ChEx_stack_2->SetBinContent(42,2);
   hist_fate_ChEx_stack_2->SetBinContent(43,9);
   hist_fate_ChEx_stack_2->SetBinContent(44,5);
   hist_fate_ChEx_stack_2->SetBinContent(45,3);
   hist_fate_ChEx_stack_2->SetBinContent(46,1);
   hist_fate_ChEx_stack_2->SetBinContent(47,1);
   hist_fate_ChEx_stack_2->SetBinContent(48,1);
   hist_fate_ChEx_stack_2->SetBinContent(49,2);
   hist_fate_ChEx_stack_2->SetBinContent(50,2);
   hist_fate_ChEx_stack_2->SetBinContent(51,44);
   hist_fate_ChEx_stack_2->SetEntries(8344);
   hist_fate_ChEx_stack_2->SetDirectory(nullptr);

   ci = TColor::GetColor("#0000ff");
   hist_fate_ChEx_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   hist_fate_ChEx_stack_2->SetLineColor(ci);
   hist_fate_ChEx_stack_2->GetXaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetXaxis()->SetTitleOffset(1);
   hist_fate_ChEx_stack_2->GetXaxis()->SetTitleFont(42);
   hist_fate_ChEx_stack_2->GetYaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetYaxis()->SetTitleFont(42);
   hist_fate_ChEx_stack_2->GetZaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetZaxis()->SetTitleOffset(1);
   hist_fate_ChEx_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_ChEx_stack_2,"");
   
   TH1D *hist_fate_Elas_stack_3 = new TH1D("hist_fate_Elas_stack_3","KE - No Elas (Elas)",50,0,2000);
   hist_fate_Elas_stack_3->SetBinContent(0,12615);
   hist_fate_Elas_stack_3->SetBinContent(1,4257);
   hist_fate_Elas_stack_3->SetBinContent(2,6379);
   hist_fate_Elas_stack_3->SetBinContent(3,6561);
   hist_fate_Elas_stack_3->SetBinContent(4,6288);
   hist_fate_Elas_stack_3->SetBinContent(5,6798);
   hist_fate_Elas_stack_3->SetBinContent(6,7438);
   hist_fate_Elas_stack_3->SetBinContent(7,7577);
   hist_fate_Elas_stack_3->SetBinContent(8,6482);
   hist_fate_Elas_stack_3->SetBinContent(9,5920);
   hist_fate_Elas_stack_3->SetBinContent(10,5547);
   hist_fate_Elas_stack_3->SetBinContent(11,4700);
   hist_fate_Elas_stack_3->SetBinContent(12,3953);
   hist_fate_Elas_stack_3->SetBinContent(13,3018);
   hist_fate_Elas_stack_3->SetBinContent(14,2639);
   hist_fate_Elas_stack_3->SetBinContent(15,2047);
   hist_fate_Elas_stack_3->SetBinContent(16,1715);
   hist_fate_Elas_stack_3->SetBinContent(17,1482);
   hist_fate_Elas_stack_3->SetBinContent(18,1234);
   hist_fate_Elas_stack_3->SetBinContent(19,935);
   hist_fate_Elas_stack_3->SetBinContent(20,821);
   hist_fate_Elas_stack_3->SetBinContent(21,727);
   hist_fate_Elas_stack_3->SetBinContent(22,603);
   hist_fate_Elas_stack_3->SetBinContent(23,575);
   hist_fate_Elas_stack_3->SetBinContent(24,677);
   hist_fate_Elas_stack_3->SetBinContent(25,1172);
   hist_fate_Elas_stack_3->SetBinContent(26,942);
   hist_fate_Elas_stack_3->SetBinContent(27,762);
   hist_fate_Elas_stack_3->SetBinContent(28,775);
   hist_fate_Elas_stack_3->SetBinContent(29,726);
   hist_fate_Elas_stack_3->SetBinContent(30,756);
   hist_fate_Elas_stack_3->SetBinContent(31,568);
   hist_fate_Elas_stack_3->SetBinContent(32,668);
   hist_fate_Elas_stack_3->SetBinContent(33,400);
   hist_fate_Elas_stack_3->SetBinContent(34,478);
   hist_fate_Elas_stack_3->SetBinContent(35,408);
   hist_fate_Elas_stack_3->SetBinContent(36,309);
   hist_fate_Elas_stack_3->SetBinContent(37,334);
   hist_fate_Elas_stack_3->SetBinContent(38,305);
   hist_fate_Elas_stack_3->SetBinContent(39,278);
   hist_fate_Elas_stack_3->SetBinContent(40,289);
   hist_fate_Elas_stack_3->SetBinContent(41,192);
   hist_fate_Elas_stack_3->SetBinContent(42,187);
   hist_fate_Elas_stack_3->SetBinContent(43,170);
   hist_fate_Elas_stack_3->SetBinContent(44,141);
   hist_fate_Elas_stack_3->SetBinContent(45,114);
   hist_fate_Elas_stack_3->SetBinContent(46,146);
   hist_fate_Elas_stack_3->SetBinContent(47,107);
   hist_fate_Elas_stack_3->SetBinContent(48,116);
   hist_fate_Elas_stack_3->SetBinContent(49,71);
   hist_fate_Elas_stack_3->SetBinContent(50,96);
   hist_fate_Elas_stack_3->SetBinContent(51,842);
   hist_fate_Elas_stack_3->SetEntries(112340);
   hist_fate_Elas_stack_3->SetDirectory(nullptr);

   ci = TColor::GetColor("#00ff00");
   hist_fate_Elas_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   hist_fate_Elas_stack_3->SetLineColor(ci);
   hist_fate_Elas_stack_3->GetXaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetXaxis()->SetTitleOffset(1);
   hist_fate_Elas_stack_3->GetXaxis()->SetTitleFont(42);
   hist_fate_Elas_stack_3->GetYaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetYaxis()->SetTitleFont(42);
   hist_fate_Elas_stack_3->GetZaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetZaxis()->SetTitleOffset(1);
   hist_fate_Elas_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_Elas_stack_3,"");
   
   TH1D *hist_fate_Abs_stack_4 = new TH1D("hist_fate_Abs_stack_4","KE - No Abs (Abs)",50,0,2000);
   hist_fate_Abs_stack_4->SetBinContent(0,10695);
   hist_fate_Abs_stack_4->SetBinContent(1,2746);
   hist_fate_Abs_stack_4->SetBinContent(2,3555);
   hist_fate_Abs_stack_4->SetBinContent(3,4116);
   hist_fate_Abs_stack_4->SetBinContent(4,4320);
   hist_fate_Abs_stack_4->SetBinContent(5,5466);
   hist_fate_Abs_stack_4->SetBinContent(6,5314);
   hist_fate_Abs_stack_4->SetBinContent(7,4941);
   hist_fate_Abs_stack_4->SetBinContent(8,5193);
   hist_fate_Abs_stack_4->SetBinContent(9,4590);
   hist_fate_Abs_stack_4->SetBinContent(10,4016);
   hist_fate_Abs_stack_4->SetBinContent(11,3457);
   hist_fate_Abs_stack_4->SetBinContent(12,3040);
   hist_fate_Abs_stack_4->SetBinContent(13,2521);
   hist_fate_Abs_stack_4->SetBinContent(14,2487);
   hist_fate_Abs_stack_4->SetBinContent(15,2394);
   hist_fate_Abs_stack_4->SetBinContent(16,2034);
   hist_fate_Abs_stack_4->SetBinContent(17,1852);
   hist_fate_Abs_stack_4->SetBinContent(18,1733);
   hist_fate_Abs_stack_4->SetBinContent(19,1507);
   hist_fate_Abs_stack_4->SetBinContent(20,1505);
   hist_fate_Abs_stack_4->SetBinContent(21,1217);
   hist_fate_Abs_stack_4->SetBinContent(22,1142);
   hist_fate_Abs_stack_4->SetBinContent(23,1119);
   hist_fate_Abs_stack_4->SetBinContent(24,1035);
   hist_fate_Abs_stack_4->SetBinContent(25,1231);
   hist_fate_Abs_stack_4->SetBinContent(26,1136);
   hist_fate_Abs_stack_4->SetBinContent(27,1058);
   hist_fate_Abs_stack_4->SetBinContent(28,881);
   hist_fate_Abs_stack_4->SetBinContent(29,856);
   hist_fate_Abs_stack_4->SetBinContent(30,807);
   hist_fate_Abs_stack_4->SetBinContent(31,737);
   hist_fate_Abs_stack_4->SetBinContent(32,642);
   hist_fate_Abs_stack_4->SetBinContent(33,589);
   hist_fate_Abs_stack_4->SetBinContent(34,503);
   hist_fate_Abs_stack_4->SetBinContent(35,574);
   hist_fate_Abs_stack_4->SetBinContent(36,473);
   hist_fate_Abs_stack_4->SetBinContent(37,391);
   hist_fate_Abs_stack_4->SetBinContent(38,394);
   hist_fate_Abs_stack_4->SetBinContent(39,375);
   hist_fate_Abs_stack_4->SetBinContent(40,331);
   hist_fate_Abs_stack_4->SetBinContent(41,309);
   hist_fate_Abs_stack_4->SetBinContent(42,326);
   hist_fate_Abs_stack_4->SetBinContent(43,221);
   hist_fate_Abs_stack_4->SetBinContent(44,230);
   hist_fate_Abs_stack_4->SetBinContent(45,253);
   hist_fate_Abs_stack_4->SetBinContent(46,169);
   hist_fate_Abs_stack_4->SetBinContent(47,213);
   hist_fate_Abs_stack_4->SetBinContent(48,169);
   hist_fate_Abs_stack_4->SetBinContent(49,159);
   hist_fate_Abs_stack_4->SetBinContent(50,139);
   hist_fate_Abs_stack_4->SetBinContent(51,1687);
   hist_fate_Abs_stack_4->SetEntries(96848);
   hist_fate_Abs_stack_4->SetDirectory(nullptr);

   ci = TColor::GetColor("#ff00ff");
   hist_fate_Abs_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   hist_fate_Abs_stack_4->SetLineColor(ci);
   hist_fate_Abs_stack_4->GetXaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetXaxis()->SetTitleOffset(1);
   hist_fate_Abs_stack_4->GetXaxis()->SetTitleFont(42);
   hist_fate_Abs_stack_4->GetYaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetYaxis()->SetTitleFont(42);
   hist_fate_Abs_stack_4->GetZaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetZaxis()->SetTitleOffset(1);
   hist_fate_Abs_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_Abs_stack_4,"");
   
   TH1D *hist_fate_PionP_stack_5 = new TH1D("hist_fate_PionP_stack_5","KE - No PionP (PionP)",50,0,2000);
   hist_fate_PionP_stack_5->SetBinContent(0,62);
   hist_fate_PionP_stack_5->SetBinContent(1,40);
   hist_fate_PionP_stack_5->SetBinContent(2,74);
   hist_fate_PionP_stack_5->SetBinContent(3,74);
   hist_fate_PionP_stack_5->SetBinContent(4,101);
   hist_fate_PionP_stack_5->SetBinContent(5,131);
   hist_fate_PionP_stack_5->SetBinContent(6,109);
   hist_fate_PionP_stack_5->SetBinContent(7,146);
   hist_fate_PionP_stack_5->SetBinContent(8,176);
   hist_fate_PionP_stack_5->SetBinContent(9,248);
   hist_fate_PionP_stack_5->SetBinContent(10,280);
   hist_fate_PionP_stack_5->SetBinContent(11,384);
   hist_fate_PionP_stack_5->SetBinContent(12,464);
   hist_fate_PionP_stack_5->SetBinContent(13,517);
   hist_fate_PionP_stack_5->SetBinContent(14,685);
   hist_fate_PionP_stack_5->SetBinContent(15,690);
   hist_fate_PionP_stack_5->SetBinContent(16,749);
   hist_fate_PionP_stack_5->SetBinContent(17,753);
   hist_fate_PionP_stack_5->SetBinContent(18,836);
   hist_fate_PionP_stack_5->SetBinContent(19,727);
   hist_fate_PionP_stack_5->SetBinContent(20,777);
   hist_fate_PionP_stack_5->SetBinContent(21,786);
   hist_fate_PionP_stack_5->SetBinContent(22,699);
   hist_fate_PionP_stack_5->SetBinContent(23,764);
   hist_fate_PionP_stack_5->SetBinContent(24,704);
   hist_fate_PionP_stack_5->SetBinContent(25,643);
   hist_fate_PionP_stack_5->SetBinContent(26,583);
   hist_fate_PionP_stack_5->SetBinContent(27,532);
   hist_fate_PionP_stack_5->SetBinContent(28,470);
   hist_fate_PionP_stack_5->SetBinContent(29,518);
   hist_fate_PionP_stack_5->SetBinContent(30,483);
   hist_fate_PionP_stack_5->SetBinContent(31,367);
   hist_fate_PionP_stack_5->SetBinContent(32,410);
   hist_fate_PionP_stack_5->SetBinContent(33,373);
   hist_fate_PionP_stack_5->SetBinContent(34,321);
   hist_fate_PionP_stack_5->SetBinContent(35,331);
   hist_fate_PionP_stack_5->SetBinContent(36,272);
   hist_fate_PionP_stack_5->SetBinContent(37,203);
   hist_fate_PionP_stack_5->SetBinContent(38,308);
   hist_fate_PionP_stack_5->SetBinContent(39,336);
   hist_fate_PionP_stack_5->SetBinContent(40,220);
   hist_fate_PionP_stack_5->SetBinContent(41,232);
   hist_fate_PionP_stack_5->SetBinContent(42,254);
   hist_fate_PionP_stack_5->SetBinContent(43,175);
   hist_fate_PionP_stack_5->SetBinContent(44,188);
   hist_fate_PionP_stack_5->SetBinContent(45,177);
   hist_fate_PionP_stack_5->SetBinContent(46,170);
   hist_fate_PionP_stack_5->SetBinContent(47,159);
   hist_fate_PionP_stack_5->SetBinContent(48,162);
   hist_fate_PionP_stack_5->SetBinContent(49,102);
   hist_fate_PionP_stack_5->SetBinContent(50,132);
   hist_fate_PionP_stack_5->SetBinContent(51,1603);
   hist_fate_PionP_stack_5->SetEntries(20700);
   hist_fate_PionP_stack_5->SetDirectory(nullptr);

   ci = TColor::GetColor("#00ffff");
   hist_fate_PionP_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   hist_fate_PionP_stack_5->SetLineColor(ci);
   hist_fate_PionP_stack_5->GetXaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetXaxis()->SetTitleOffset(1);
   hist_fate_PionP_stack_5->GetXaxis()->SetTitleFont(42);
   hist_fate_PionP_stack_5->GetYaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetYaxis()->SetTitleFont(42);
   hist_fate_PionP_stack_5->GetZaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetZaxis()->SetTitleOffset(1);
   hist_fate_PionP_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_PionP_stack_5,"");
   
   TH1D *hist_fate_MultN_stack_6 = new TH1D("hist_fate_MultN_stack_6","KE - No MultN (MN)",50,0,2000);
   hist_fate_MultN_stack_6->SetBinContent(1,360);
   hist_fate_MultN_stack_6->SetBinContent(2,612);
   hist_fate_MultN_stack_6->SetBinContent(3,828);
   hist_fate_MultN_stack_6->SetBinContent(4,824);
   hist_fate_MultN_stack_6->SetBinContent(5,792);
   hist_fate_MultN_stack_6->SetBinContent(6,740);
   hist_fate_MultN_stack_6->SetBinContent(7,720);
   hist_fate_MultN_stack_6->SetBinContent(8,696);
   hist_fate_MultN_stack_6->SetBinContent(9,636);
   hist_fate_MultN_stack_6->SetBinContent(10,604);
   hist_fate_MultN_stack_6->SetBinContent(11,588);
   hist_fate_MultN_stack_6->SetBinContent(12,540);
   hist_fate_MultN_stack_6->SetBinContent(13,516);
   hist_fate_MultN_stack_6->SetBinContent(14,428);
   hist_fate_MultN_stack_6->SetBinContent(15,408);
   hist_fate_MultN_stack_6->SetBinContent(16,344);
   hist_fate_MultN_stack_6->SetBinContent(17,340);
   hist_fate_MultN_stack_6->SetBinContent(18,244);
   hist_fate_MultN_stack_6->SetBinContent(19,280);
   hist_fate_MultN_stack_6->SetBinContent(20,216);
   hist_fate_MultN_stack_6->SetBinContent(21,232);
   hist_fate_MultN_stack_6->SetBinContent(22,184);
   hist_fate_MultN_stack_6->SetBinContent(23,136);
   hist_fate_MultN_stack_6->SetBinContent(24,172);
   hist_fate_MultN_stack_6->SetBinContent(25,212);
   hist_fate_MultN_stack_6->SetBinContent(26,232);
   hist_fate_MultN_stack_6->SetBinContent(27,176);
   hist_fate_MultN_stack_6->SetBinContent(28,184);
   hist_fate_MultN_stack_6->SetBinContent(29,192);
   hist_fate_MultN_stack_6->SetBinContent(30,200);
   hist_fate_MultN_stack_6->SetBinContent(31,180);
   hist_fate_MultN_stack_6->SetBinContent(32,128);
   hist_fate_MultN_stack_6->SetBinContent(33,172);
   hist_fate_MultN_stack_6->SetBinContent(34,156);
   hist_fate_MultN_stack_6->SetBinContent(35,156);
   hist_fate_MultN_stack_6->SetBinContent(36,132);
   hist_fate_MultN_stack_6->SetBinContent(37,100);
   hist_fate_MultN_stack_6->SetBinContent(38,112);
   hist_fate_MultN_stack_6->SetBinContent(39,104);
   hist_fate_MultN_stack_6->SetBinContent(40,72);
   hist_fate_MultN_stack_6->SetBinContent(41,72);
   hist_fate_MultN_stack_6->SetBinContent(42,96);
   hist_fate_MultN_stack_6->SetBinContent(43,72);
   hist_fate_MultN_stack_6->SetBinContent(44,52);
   hist_fate_MultN_stack_6->SetBinContent(45,40);
   hist_fate_MultN_stack_6->SetBinContent(46,40);
   hist_fate_MultN_stack_6->SetBinContent(47,32);
   hist_fate_MultN_stack_6->SetBinContent(48,48);
   hist_fate_MultN_stack_6->SetBinContent(49,20);
   hist_fate_MultN_stack_6->SetBinContent(50,52);
   hist_fate_MultN_stack_6->SetBinContent(51,412);
   hist_fate_MultN_stack_6->SetEntries(14884);
   hist_fate_MultN_stack_6->SetDirectory(nullptr);

   ci = TColor::GetColor("#cccc00");
   hist_fate_MultN_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#cccc00");
   hist_fate_MultN_stack_6->SetLineColor(ci);
   hist_fate_MultN_stack_6->GetXaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetXaxis()->SetTitleOffset(1);
   hist_fate_MultN_stack_6->GetXaxis()->SetTitleFont(42);
   hist_fate_MultN_stack_6->GetYaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetYaxis()->SetTitleFont(42);
   hist_fate_MultN_stack_6->GetZaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetZaxis()->SetTitleOffset(1);
   hist_fate_MultN_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_MultN_stack_6,"");
   
   TH1D *hist_fate_KnockOut_stack_7 = new TH1D("hist_fate_KnockOut_stack_7","KE - KnockOut (KnockOut)",50,0,2000);
   hist_fate_KnockOut_stack_7->SetBinContent(1,1008);
   hist_fate_KnockOut_stack_7->SetBinContent(2,3836);
   hist_fate_KnockOut_stack_7->SetBinContent(3,3628);
   hist_fate_KnockOut_stack_7->SetBinContent(4,3440);
   hist_fate_KnockOut_stack_7->SetBinContent(5,3048);
   hist_fate_KnockOut_stack_7->SetBinContent(6,2844);
   hist_fate_KnockOut_stack_7->SetBinContent(7,2396);
   hist_fate_KnockOut_stack_7->SetBinContent(8,2084);
   hist_fate_KnockOut_stack_7->SetBinContent(9,1836);
   hist_fate_KnockOut_stack_7->SetBinContent(10,1768);
   hist_fate_KnockOut_stack_7->SetBinContent(11,1556);
   hist_fate_KnockOut_stack_7->SetBinContent(12,1300);
   hist_fate_KnockOut_stack_7->SetBinContent(13,1144);
   hist_fate_KnockOut_stack_7->SetBinContent(14,1036);
   hist_fate_KnockOut_stack_7->SetBinContent(15,884);
   hist_fate_KnockOut_stack_7->SetBinContent(16,908);
   hist_fate_KnockOut_stack_7->SetBinContent(17,784);
   hist_fate_KnockOut_stack_7->SetBinContent(18,704);
   hist_fate_KnockOut_stack_7->SetBinContent(19,512);
   hist_fate_KnockOut_stack_7->SetBinContent(20,640);
   hist_fate_KnockOut_stack_7->SetBinContent(21,472);
   hist_fate_KnockOut_stack_7->SetBinContent(22,448);
   hist_fate_KnockOut_stack_7->SetBinContent(23,384);
   hist_fate_KnockOut_stack_7->SetBinContent(24,332);
   hist_fate_KnockOut_stack_7->SetBinContent(25,660);
   hist_fate_KnockOut_stack_7->SetBinContent(26,840);
   hist_fate_KnockOut_stack_7->SetBinContent(27,880);
   hist_fate_KnockOut_stack_7->SetBinContent(28,680);
   hist_fate_KnockOut_stack_7->SetBinContent(29,616);
   hist_fate_KnockOut_stack_7->SetBinContent(30,660);
   hist_fate_KnockOut_stack_7->SetBinContent(31,540);
   hist_fate_KnockOut_stack_7->SetBinContent(32,536);
   hist_fate_KnockOut_stack_7->SetBinContent(33,548);
   hist_fate_KnockOut_stack_7->SetBinContent(34,428);
   hist_fate_KnockOut_stack_7->SetBinContent(35,364);
   hist_fate_KnockOut_stack_7->SetBinContent(36,276);
   hist_fate_KnockOut_stack_7->SetBinContent(37,308);
   hist_fate_KnockOut_stack_7->SetBinContent(38,276);
   hist_fate_KnockOut_stack_7->SetBinContent(39,256);
   hist_fate_KnockOut_stack_7->SetBinContent(40,252);
   hist_fate_KnockOut_stack_7->SetBinContent(41,180);
   hist_fate_KnockOut_stack_7->SetBinContent(42,176);
   hist_fate_KnockOut_stack_7->SetBinContent(43,152);
   hist_fate_KnockOut_stack_7->SetBinContent(44,188);
   hist_fate_KnockOut_stack_7->SetBinContent(45,124);
   hist_fate_KnockOut_stack_7->SetBinContent(46,112);
   hist_fate_KnockOut_stack_7->SetBinContent(47,144);
   hist_fate_KnockOut_stack_7->SetBinContent(48,84);
   hist_fate_KnockOut_stack_7->SetBinContent(49,52);
   hist_fate_KnockOut_stack_7->SetBinContent(50,84);
   hist_fate_KnockOut_stack_7->SetBinContent(51,992);
   hist_fate_KnockOut_stack_7->SetEntries(47400);
   hist_fate_KnockOut_stack_7->SetDirectory(nullptr);

   ci = TColor::GetColor("#ffcc00");
   hist_fate_KnockOut_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc00");
   hist_fate_KnockOut_stack_7->SetLineColor(ci);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetTitleOffset(1);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetTitleFont(42);
   hist_fate_KnockOut_stack_7->GetYaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetYaxis()->SetTitleFont(42);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetTitleOffset(1);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_KnockOut_stack_7,"");
   hs->Draw("hist");
   
   TLegend *leg = new TLegend(0.7,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hist_fate_NC","NS","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_ChEx","ChEx","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_Elas","Elas","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_Abs","Abs","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_PionP","PionP","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_MultN","MultN","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_KnockOut","KnockOut","f");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
