#ifdef __CLING__
#pragma cling optimize(0)
#endif
void KE()
{
//=========Macro generated from canvas: c/Stacked Histograms
//=========  (Wed Dec  4 23:09:09 2024) by ROOT version 6.28/12
   TCanvas *c = new TCanvas("c", "Stacked Histograms",0,0,800,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->SetHighLightColor(2);
   c->Range(-375,-805.7778,2125,4949.778);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.15);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.05);
   c->SetBottomMargin(0.14);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   THStack *hs = new THStack();
   hs->SetName("hs");
   hs->SetTitle("Stacked Histograms;Kinetic Energy (MeV);Events");
   
   TH1F *hs_stack_1 = new TH1F("hs_stack_1","Stacked Histograms",50,0,2000);
   hs_stack_1->SetMinimum(0);
   hs_stack_1->SetMaximum(4662);
   hs_stack_1->SetDirectory(nullptr);
   hs_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_stack_1->SetLineColor(ci);
   hs_stack_1->SetLineWidth(0);
   hs_stack_1->GetXaxis()->SetTitle("Kinetic Energy (MeV)");
   hs_stack_1->GetXaxis()->SetLabelFont(42);
   hs_stack_1->GetXaxis()->SetLabelSize(0.04);
   hs_stack_1->GetXaxis()->SetTitleSize(0.06);
   hs_stack_1->GetXaxis()->SetTickLength(0.02);
   hs_stack_1->GetXaxis()->SetTitleOffset(1);
   hs_stack_1->GetXaxis()->SetTitleFont(42);
   hs_stack_1->GetYaxis()->SetTitle("Events");
   hs_stack_1->GetYaxis()->SetLabelFont(42);
   hs_stack_1->GetYaxis()->SetLabelSize(0.04);
   hs_stack_1->GetYaxis()->SetTitleSize(0.06);
   hs_stack_1->GetYaxis()->SetTickLength(0.01);
   hs_stack_1->GetYaxis()->SetTitleOffset(0.9);
   hs_stack_1->GetYaxis()->SetTitleFont(42);
   hs_stack_1->GetZaxis()->SetLabelFont(42);
   hs_stack_1->GetZaxis()->SetLabelSize(0.04);
   hs_stack_1->GetZaxis()->SetTitleSize(0.06);
   hs_stack_1->GetZaxis()->SetTitleOffset(1);
   hs_stack_1->GetZaxis()->SetTitleFont(42);
   hs->SetHistogram(hs_stack_1);
   
   
   TH1D *hist_fate_NC_stack_1 = new TH1D("hist_fate_NC_stack_1","KE - No Interaction (NS)",50,0,2000);
   hist_fate_NC_stack_1->SetBinContent(2,40);
   hist_fate_NC_stack_1->SetBinContent(3,100);
   hist_fate_NC_stack_1->SetBinContent(4,160);
   hist_fate_NC_stack_1->SetBinContent(5,240);
   hist_fate_NC_stack_1->SetBinContent(6,248);
   hist_fate_NC_stack_1->SetBinContent(7,284);
   hist_fate_NC_stack_1->SetBinContent(8,220);
   hist_fate_NC_stack_1->SetBinContent(9,240);
   hist_fate_NC_stack_1->SetBinContent(10,216);
   hist_fate_NC_stack_1->SetBinContent(11,152);
   hist_fate_NC_stack_1->SetBinContent(12,116);
   hist_fate_NC_stack_1->SetBinContent(13,92);
   hist_fate_NC_stack_1->SetBinContent(14,108);
   hist_fate_NC_stack_1->SetBinContent(15,64);
   hist_fate_NC_stack_1->SetBinContent(16,72);
   hist_fate_NC_stack_1->SetBinContent(17,60);
   hist_fate_NC_stack_1->SetBinContent(18,40);
   hist_fate_NC_stack_1->SetBinContent(19,44);
   hist_fate_NC_stack_1->SetBinContent(20,24);
   hist_fate_NC_stack_1->SetBinContent(21,24);
   hist_fate_NC_stack_1->SetBinContent(22,36);
   hist_fate_NC_stack_1->SetBinContent(23,32);
   hist_fate_NC_stack_1->SetBinContent(24,28);
   hist_fate_NC_stack_1->SetBinContent(25,12);
   hist_fate_NC_stack_1->SetBinContent(26,8);
   hist_fate_NC_stack_1->SetBinContent(27,36);
   hist_fate_NC_stack_1->SetBinContent(28,16);
   hist_fate_NC_stack_1->SetBinContent(29,16);
   hist_fate_NC_stack_1->SetBinContent(30,12);
   hist_fate_NC_stack_1->SetBinContent(31,8);
   hist_fate_NC_stack_1->SetBinContent(32,12);
   hist_fate_NC_stack_1->SetBinContent(33,16);
   hist_fate_NC_stack_1->SetBinContent(34,16);
   hist_fate_NC_stack_1->SetBinContent(35,8);
   hist_fate_NC_stack_1->SetBinContent(36,16);
   hist_fate_NC_stack_1->SetBinContent(37,12);
   hist_fate_NC_stack_1->SetBinContent(38,8);
   hist_fate_NC_stack_1->SetBinContent(39,4);
   hist_fate_NC_stack_1->SetBinContent(44,4);
   hist_fate_NC_stack_1->SetBinContent(45,4);
   hist_fate_NC_stack_1->SetBinContent(47,4);
   hist_fate_NC_stack_1->SetBinContent(48,4);
   hist_fate_NC_stack_1->SetBinContent(51,24);
   hist_fate_NC_stack_1->SetEntries(2880);
   hist_fate_NC_stack_1->SetDirectory(nullptr);

   ci = TColor::GetColor("#ff0000");
   hist_fate_NC_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   hist_fate_NC_stack_1->SetLineColor(ci);
   hist_fate_NC_stack_1->GetXaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetXaxis()->SetTitleOffset(1);
   hist_fate_NC_stack_1->GetXaxis()->SetTitleFont(42);
   hist_fate_NC_stack_1->GetYaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetYaxis()->SetTitleFont(42);
   hist_fate_NC_stack_1->GetZaxis()->SetLabelFont(42);
   hist_fate_NC_stack_1->GetZaxis()->SetTitleOffset(1);
   hist_fate_NC_stack_1->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_NC_stack_1,"");
   
   TH1D *hist_fate_ChEx_stack_2 = new TH1D("hist_fate_ChEx_stack_2","KE - No ChEx (ChEx)",50,0,2000);
   hist_fate_ChEx_stack_2->SetDirectory(nullptr);

   ci = TColor::GetColor("#0000ff");
   hist_fate_ChEx_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   hist_fate_ChEx_stack_2->SetLineColor(ci);
   hist_fate_ChEx_stack_2->GetXaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetXaxis()->SetTitleOffset(1);
   hist_fate_ChEx_stack_2->GetXaxis()->SetTitleFont(42);
   hist_fate_ChEx_stack_2->GetYaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetYaxis()->SetTitleFont(42);
   hist_fate_ChEx_stack_2->GetZaxis()->SetLabelFont(42);
   hist_fate_ChEx_stack_2->GetZaxis()->SetTitleOffset(1);
   hist_fate_ChEx_stack_2->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_ChEx_stack_2,"");
   
   TH1D *hist_fate_Elas_stack_3 = new TH1D("hist_fate_Elas_stack_3","KE - No Elas (Elas)",50,0,2000);
   hist_fate_Elas_stack_3->SetBinContent(1,536);
   hist_fate_Elas_stack_3->SetBinContent(2,1756);
   hist_fate_Elas_stack_3->SetBinContent(3,1512);
   hist_fate_Elas_stack_3->SetBinContent(4,1144);
   hist_fate_Elas_stack_3->SetBinContent(5,912);
   hist_fate_Elas_stack_3->SetBinContent(6,788);
   hist_fate_Elas_stack_3->SetBinContent(7,644);
   hist_fate_Elas_stack_3->SetBinContent(8,540);
   hist_fate_Elas_stack_3->SetBinContent(9,444);
   hist_fate_Elas_stack_3->SetBinContent(10,404);
   hist_fate_Elas_stack_3->SetBinContent(11,320);
   hist_fate_Elas_stack_3->SetBinContent(12,236);
   hist_fate_Elas_stack_3->SetBinContent(13,216);
   hist_fate_Elas_stack_3->SetBinContent(14,156);
   hist_fate_Elas_stack_3->SetBinContent(15,132);
   hist_fate_Elas_stack_3->SetBinContent(16,88);
   hist_fate_Elas_stack_3->SetBinContent(17,104);
   hist_fate_Elas_stack_3->SetBinContent(18,84);
   hist_fate_Elas_stack_3->SetBinContent(19,56);
   hist_fate_Elas_stack_3->SetBinContent(20,60);
   hist_fate_Elas_stack_3->SetBinContent(21,44);
   hist_fate_Elas_stack_3->SetBinContent(22,32);
   hist_fate_Elas_stack_3->SetBinContent(23,12);
   hist_fate_Elas_stack_3->SetBinContent(24,16);
   hist_fate_Elas_stack_3->SetBinContent(25,20);
   hist_fate_Elas_stack_3->SetBinContent(26,12);
   hist_fate_Elas_stack_3->SetBinContent(27,4);
   hist_fate_Elas_stack_3->SetBinContent(28,8);
   hist_fate_Elas_stack_3->SetBinContent(29,12);
   hist_fate_Elas_stack_3->SetBinContent(30,8);
   hist_fate_Elas_stack_3->SetBinContent(31,12);
   hist_fate_Elas_stack_3->SetBinContent(32,16);
   hist_fate_Elas_stack_3->SetBinContent(33,4);
   hist_fate_Elas_stack_3->SetBinContent(35,4);
   hist_fate_Elas_stack_3->SetBinContent(36,12);
   hist_fate_Elas_stack_3->SetBinContent(37,12);
   hist_fate_Elas_stack_3->SetBinContent(38,20);
   hist_fate_Elas_stack_3->SetBinContent(41,4);
   hist_fate_Elas_stack_3->SetBinContent(42,8);
   hist_fate_Elas_stack_3->SetBinContent(43,4);
   hist_fate_Elas_stack_3->SetBinContent(46,8);
   hist_fate_Elas_stack_3->SetBinContent(47,4);
   hist_fate_Elas_stack_3->SetBinContent(51,24);
   hist_fate_Elas_stack_3->SetEntries(10432);
   hist_fate_Elas_stack_3->SetDirectory(nullptr);

   ci = TColor::GetColor("#00ff00");
   hist_fate_Elas_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   hist_fate_Elas_stack_3->SetLineColor(ci);
   hist_fate_Elas_stack_3->GetXaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetXaxis()->SetTitleOffset(1);
   hist_fate_Elas_stack_3->GetXaxis()->SetTitleFont(42);
   hist_fate_Elas_stack_3->GetYaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetYaxis()->SetTitleFont(42);
   hist_fate_Elas_stack_3->GetZaxis()->SetLabelFont(42);
   hist_fate_Elas_stack_3->GetZaxis()->SetTitleOffset(1);
   hist_fate_Elas_stack_3->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_Elas_stack_3,"");
   
   TH1D *hist_fate_Abs_stack_4 = new TH1D("hist_fate_Abs_stack_4","KE - No Abs (Abs)",50,0,2000);
   hist_fate_Abs_stack_4->SetBinContent(1,232);
   hist_fate_Abs_stack_4->SetBinContent(2,624);
   hist_fate_Abs_stack_4->SetBinContent(3,756);
   hist_fate_Abs_stack_4->SetBinContent(4,580);
   hist_fate_Abs_stack_4->SetBinContent(5,504);
   hist_fate_Abs_stack_4->SetBinContent(6,428);
   hist_fate_Abs_stack_4->SetBinContent(7,284);
   hist_fate_Abs_stack_4->SetBinContent(8,296);
   hist_fate_Abs_stack_4->SetBinContent(9,272);
   hist_fate_Abs_stack_4->SetBinContent(10,220);
   hist_fate_Abs_stack_4->SetBinContent(11,200);
   hist_fate_Abs_stack_4->SetBinContent(12,172);
   hist_fate_Abs_stack_4->SetBinContent(13,132);
   hist_fate_Abs_stack_4->SetBinContent(14,72);
   hist_fate_Abs_stack_4->SetBinContent(15,116);
   hist_fate_Abs_stack_4->SetBinContent(16,100);
   hist_fate_Abs_stack_4->SetBinContent(17,64);
   hist_fate_Abs_stack_4->SetBinContent(18,76);
   hist_fate_Abs_stack_4->SetBinContent(19,48);
   hist_fate_Abs_stack_4->SetBinContent(20,44);
   hist_fate_Abs_stack_4->SetBinContent(21,44);
   hist_fate_Abs_stack_4->SetBinContent(22,24);
   hist_fate_Abs_stack_4->SetBinContent(23,28);
   hist_fate_Abs_stack_4->SetBinContent(24,20);
   hist_fate_Abs_stack_4->SetBinContent(25,28);
   hist_fate_Abs_stack_4->SetBinContent(26,16);
   hist_fate_Abs_stack_4->SetBinContent(27,16);
   hist_fate_Abs_stack_4->SetBinContent(28,4);
   hist_fate_Abs_stack_4->SetBinContent(29,4);
   hist_fate_Abs_stack_4->SetBinContent(30,4);
   hist_fate_Abs_stack_4->SetBinContent(31,20);
   hist_fate_Abs_stack_4->SetBinContent(32,8);
   hist_fate_Abs_stack_4->SetBinContent(33,4);
   hist_fate_Abs_stack_4->SetBinContent(34,4);
   hist_fate_Abs_stack_4->SetBinContent(35,4);
   hist_fate_Abs_stack_4->SetBinContent(36,8);
   hist_fate_Abs_stack_4->SetBinContent(37,4);
   hist_fate_Abs_stack_4->SetBinContent(39,4);
   hist_fate_Abs_stack_4->SetBinContent(40,4);
   hist_fate_Abs_stack_4->SetBinContent(41,4);
   hist_fate_Abs_stack_4->SetBinContent(42,4);
   hist_fate_Abs_stack_4->SetBinContent(44,4);
   hist_fate_Abs_stack_4->SetBinContent(51,8);
   hist_fate_Abs_stack_4->SetEntries(5488);
   hist_fate_Abs_stack_4->SetDirectory(nullptr);

   ci = TColor::GetColor("#ff00ff");
   hist_fate_Abs_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   hist_fate_Abs_stack_4->SetLineColor(ci);
   hist_fate_Abs_stack_4->GetXaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetXaxis()->SetTitleOffset(1);
   hist_fate_Abs_stack_4->GetXaxis()->SetTitleFont(42);
   hist_fate_Abs_stack_4->GetYaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetYaxis()->SetTitleFont(42);
   hist_fate_Abs_stack_4->GetZaxis()->SetLabelFont(42);
   hist_fate_Abs_stack_4->GetZaxis()->SetTitleOffset(1);
   hist_fate_Abs_stack_4->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_Abs_stack_4,"");
   
   TH1D *hist_fate_PionP_stack_5 = new TH1D("hist_fate_PionP_stack_5","KE - No PionP (PionP)",50,0,2000);
   hist_fate_PionP_stack_5->SetBinContent(8,4);
   hist_fate_PionP_stack_5->SetBinContent(9,8);
   hist_fate_PionP_stack_5->SetBinContent(10,12);
   hist_fate_PionP_stack_5->SetBinContent(11,56);
   hist_fate_PionP_stack_5->SetBinContent(12,40);
   hist_fate_PionP_stack_5->SetBinContent(13,44);
   hist_fate_PionP_stack_5->SetBinContent(14,40);
   hist_fate_PionP_stack_5->SetBinContent(15,60);
   hist_fate_PionP_stack_5->SetBinContent(16,60);
   hist_fate_PionP_stack_5->SetBinContent(17,64);
   hist_fate_PionP_stack_5->SetBinContent(18,72);
   hist_fate_PionP_stack_5->SetBinContent(19,48);
   hist_fate_PionP_stack_5->SetBinContent(20,56);
   hist_fate_PionP_stack_5->SetBinContent(21,36);
   hist_fate_PionP_stack_5->SetBinContent(22,32);
   hist_fate_PionP_stack_5->SetBinContent(23,48);
   hist_fate_PionP_stack_5->SetBinContent(24,64);
   hist_fate_PionP_stack_5->SetBinContent(25,40);
   hist_fate_PionP_stack_5->SetBinContent(26,56);
   hist_fate_PionP_stack_5->SetBinContent(27,40);
   hist_fate_PionP_stack_5->SetBinContent(28,20);
   hist_fate_PionP_stack_5->SetBinContent(29,16);
   hist_fate_PionP_stack_5->SetBinContent(30,32);
   hist_fate_PionP_stack_5->SetBinContent(31,20);
   hist_fate_PionP_stack_5->SetBinContent(32,16);
   hist_fate_PionP_stack_5->SetBinContent(33,16);
   hist_fate_PionP_stack_5->SetBinContent(34,24);
   hist_fate_PionP_stack_5->SetBinContent(35,28);
   hist_fate_PionP_stack_5->SetBinContent(36,12);
   hist_fate_PionP_stack_5->SetBinContent(37,8);
   hist_fate_PionP_stack_5->SetBinContent(38,4);
   hist_fate_PionP_stack_5->SetBinContent(39,20);
   hist_fate_PionP_stack_5->SetBinContent(40,4);
   hist_fate_PionP_stack_5->SetBinContent(41,12);
   hist_fate_PionP_stack_5->SetBinContent(42,8);
   hist_fate_PionP_stack_5->SetBinContent(43,8);
   hist_fate_PionP_stack_5->SetBinContent(44,8);
   hist_fate_PionP_stack_5->SetBinContent(45,4);
   hist_fate_PionP_stack_5->SetBinContent(47,8);
   hist_fate_PionP_stack_5->SetBinContent(49,4);
   hist_fate_PionP_stack_5->SetBinContent(50,8);
   hist_fate_PionP_stack_5->SetBinContent(51,32);
   hist_fate_PionP_stack_5->SetEntries(1192);
   hist_fate_PionP_stack_5->SetDirectory(nullptr);

   ci = TColor::GetColor("#00ffff");
   hist_fate_PionP_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   hist_fate_PionP_stack_5->SetLineColor(ci);
   hist_fate_PionP_stack_5->GetXaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetXaxis()->SetTitleOffset(1);
   hist_fate_PionP_stack_5->GetXaxis()->SetTitleFont(42);
   hist_fate_PionP_stack_5->GetYaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetYaxis()->SetTitleFont(42);
   hist_fate_PionP_stack_5->GetZaxis()->SetLabelFont(42);
   hist_fate_PionP_stack_5->GetZaxis()->SetTitleOffset(1);
   hist_fate_PionP_stack_5->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_PionP_stack_5,"");
   
   TH1D *hist_fate_MultN_stack_6 = new TH1D("hist_fate_MultN_stack_6","KE - No MultN (MN)",50,0,2000);
   hist_fate_MultN_stack_6->SetBinContent(1,72);
   hist_fate_MultN_stack_6->SetBinContent(2,304);
   hist_fate_MultN_stack_6->SetBinContent(3,256);
   hist_fate_MultN_stack_6->SetBinContent(4,220);
   hist_fate_MultN_stack_6->SetBinContent(5,176);
   hist_fate_MultN_stack_6->SetBinContent(6,188);
   hist_fate_MultN_stack_6->SetBinContent(7,128);
   hist_fate_MultN_stack_6->SetBinContent(8,152);
   hist_fate_MultN_stack_6->SetBinContent(9,156);
   hist_fate_MultN_stack_6->SetBinContent(10,100);
   hist_fate_MultN_stack_6->SetBinContent(11,116);
   hist_fate_MultN_stack_6->SetBinContent(12,92);
   hist_fate_MultN_stack_6->SetBinContent(13,44);
   hist_fate_MultN_stack_6->SetBinContent(14,48);
   hist_fate_MultN_stack_6->SetBinContent(15,60);
   hist_fate_MultN_stack_6->SetBinContent(16,80);
   hist_fate_MultN_stack_6->SetBinContent(17,60);
   hist_fate_MultN_stack_6->SetBinContent(18,44);
   hist_fate_MultN_stack_6->SetBinContent(19,52);
   hist_fate_MultN_stack_6->SetBinContent(20,40);
   hist_fate_MultN_stack_6->SetBinContent(21,40);
   hist_fate_MultN_stack_6->SetBinContent(22,24);
   hist_fate_MultN_stack_6->SetBinContent(23,36);
   hist_fate_MultN_stack_6->SetBinContent(24,8);
   hist_fate_MultN_stack_6->SetBinContent(25,32);
   hist_fate_MultN_stack_6->SetBinContent(26,24);
   hist_fate_MultN_stack_6->SetBinContent(27,8);
   hist_fate_MultN_stack_6->SetBinContent(28,12);
   hist_fate_MultN_stack_6->SetBinContent(29,12);
   hist_fate_MultN_stack_6->SetBinContent(30,12);
   hist_fate_MultN_stack_6->SetBinContent(31,4);
   hist_fate_MultN_stack_6->SetBinContent(32,12);
   hist_fate_MultN_stack_6->SetBinContent(34,4);
   hist_fate_MultN_stack_6->SetBinContent(35,8);
   hist_fate_MultN_stack_6->SetBinContent(37,8);
   hist_fate_MultN_stack_6->SetBinContent(38,8);
   hist_fate_MultN_stack_6->SetBinContent(39,4);
   hist_fate_MultN_stack_6->SetBinContent(40,4);
   hist_fate_MultN_stack_6->SetBinContent(43,8);
   hist_fate_MultN_stack_6->SetBinContent(48,4);
   hist_fate_MultN_stack_6->SetBinContent(50,4);
   hist_fate_MultN_stack_6->SetBinContent(51,36);
   hist_fate_MultN_stack_6->SetEntries(2700);
   hist_fate_MultN_stack_6->SetDirectory(nullptr);

   ci = TColor::GetColor("#cccc00");
   hist_fate_MultN_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#cccc00");
   hist_fate_MultN_stack_6->SetLineColor(ci);
   hist_fate_MultN_stack_6->GetXaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetXaxis()->SetTitleOffset(1);
   hist_fate_MultN_stack_6->GetXaxis()->SetTitleFont(42);
   hist_fate_MultN_stack_6->GetYaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetYaxis()->SetTitleFont(42);
   hist_fate_MultN_stack_6->GetZaxis()->SetLabelFont(42);
   hist_fate_MultN_stack_6->GetZaxis()->SetTitleOffset(1);
   hist_fate_MultN_stack_6->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_MultN_stack_6,"");
   
   TH1D *hist_fate_KnockOut_stack_7 = new TH1D("hist_fate_KnockOut_stack_7","KE - KnockOut (KnockOut)",50,0,2000);
   hist_fate_KnockOut_stack_7->SetBinContent(1,312);
   hist_fate_KnockOut_stack_7->SetBinContent(2,1716);
   hist_fate_KnockOut_stack_7->SetBinContent(3,1304);
   hist_fate_KnockOut_stack_7->SetBinContent(4,1148);
   hist_fate_KnockOut_stack_7->SetBinContent(5,824);
   hist_fate_KnockOut_stack_7->SetBinContent(6,668);
   hist_fate_KnockOut_stack_7->SetBinContent(7,528);
   hist_fate_KnockOut_stack_7->SetBinContent(8,504);
   hist_fate_KnockOut_stack_7->SetBinContent(9,316);
   hist_fate_KnockOut_stack_7->SetBinContent(10,344);
   hist_fate_KnockOut_stack_7->SetBinContent(11,316);
   hist_fate_KnockOut_stack_7->SetBinContent(12,188);
   hist_fate_KnockOut_stack_7->SetBinContent(13,228);
   hist_fate_KnockOut_stack_7->SetBinContent(14,156);
   hist_fate_KnockOut_stack_7->SetBinContent(15,176);
   hist_fate_KnockOut_stack_7->SetBinContent(16,140);
   hist_fate_KnockOut_stack_7->SetBinContent(17,132);
   hist_fate_KnockOut_stack_7->SetBinContent(18,84);
   hist_fate_KnockOut_stack_7->SetBinContent(19,96);
   hist_fate_KnockOut_stack_7->SetBinContent(20,92);
   hist_fate_KnockOut_stack_7->SetBinContent(21,56);
   hist_fate_KnockOut_stack_7->SetBinContent(22,64);
   hist_fate_KnockOut_stack_7->SetBinContent(23,68);
   hist_fate_KnockOut_stack_7->SetBinContent(24,56);
   hist_fate_KnockOut_stack_7->SetBinContent(25,44);
   hist_fate_KnockOut_stack_7->SetBinContent(26,44);
   hist_fate_KnockOut_stack_7->SetBinContent(27,48);
   hist_fate_KnockOut_stack_7->SetBinContent(28,44);
   hist_fate_KnockOut_stack_7->SetBinContent(29,28);
   hist_fate_KnockOut_stack_7->SetBinContent(30,40);
   hist_fate_KnockOut_stack_7->SetBinContent(31,12);
   hist_fate_KnockOut_stack_7->SetBinContent(32,20);
   hist_fate_KnockOut_stack_7->SetBinContent(33,4);
   hist_fate_KnockOut_stack_7->SetBinContent(34,16);
   hist_fate_KnockOut_stack_7->SetBinContent(35,12);
   hist_fate_KnockOut_stack_7->SetBinContent(36,8);
   hist_fate_KnockOut_stack_7->SetBinContent(38,4);
   hist_fate_KnockOut_stack_7->SetBinContent(39,16);
   hist_fate_KnockOut_stack_7->SetBinContent(40,4);
   hist_fate_KnockOut_stack_7->SetBinContent(42,12);
   hist_fate_KnockOut_stack_7->SetBinContent(43,12);
   hist_fate_KnockOut_stack_7->SetBinContent(44,4);
   hist_fate_KnockOut_stack_7->SetBinContent(45,4);
   hist_fate_KnockOut_stack_7->SetBinContent(47,12);
   hist_fate_KnockOut_stack_7->SetBinContent(48,4);
   hist_fate_KnockOut_stack_7->SetBinContent(50,4);
   hist_fate_KnockOut_stack_7->SetBinContent(51,28);
   hist_fate_KnockOut_stack_7->SetEntries(9940);
   hist_fate_KnockOut_stack_7->SetDirectory(nullptr);

   ci = TColor::GetColor("#ffcc00");
   hist_fate_KnockOut_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc00");
   hist_fate_KnockOut_stack_7->SetLineColor(ci);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetTitleOffset(1);
   hist_fate_KnockOut_stack_7->GetXaxis()->SetTitleFont(42);
   hist_fate_KnockOut_stack_7->GetYaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetYaxis()->SetTitleFont(42);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetLabelFont(42);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetTitleOffset(1);
   hist_fate_KnockOut_stack_7->GetZaxis()->SetTitleFont(42);
   hs->Add(hist_fate_KnockOut_stack_7,"");
   hs->Draw("hist");
   
   TLegend *leg = new TLegend(0.7,0.7,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("hist_fate_NC","NS","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_ChEx","ChEx","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_Elas","Elas","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_Abs","Abs","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_PionP","PionP","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_MultN","MultN","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_fate_KnockOut","KnockOut","f");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
