/********************************************************************
* GridCanvas_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GridCanvas_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGridCanvas_Dict();
extern void G__cpp_setup_inheritanceGridCanvas_Dict();
extern void G__cpp_setup_typetableGridCanvas_Dict();
extern void G__cpp_setup_memvarGridCanvas_Dict();
extern void G__cpp_setup_globalGridCanvas_Dict();
extern void G__cpp_setup_memfuncGridCanvas_Dict();
extern void G__cpp_setup_funcGridCanvas_Dict();
extern void G__set_cpp_environmentGridCanvas_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GridCanvas.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GridCanvas_DictLN_TClass;
extern G__linked_taginfo G__GridCanvas_DictLN_TBuffer;
extern G__linked_taginfo G__GridCanvas_DictLN_TMemberInspector;
extern G__linked_taginfo G__GridCanvas_DictLN_TObject;
extern G__linked_taginfo G__GridCanvas_DictLN_TString;
extern G__linked_taginfo G__GridCanvas_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GridCanvas_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GridCanvas_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GridCanvas_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GridCanvas_DictLN_TAttPad;
extern G__linked_taginfo G__GridCanvas_DictLN_TAttLine;
extern G__linked_taginfo G__GridCanvas_DictLN_TAttFill;
extern G__linked_taginfo G__GridCanvas_DictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GridCanvas_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GridCanvas_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GridCanvas_DictLN_TQObject;
extern G__linked_taginfo G__GridCanvas_DictLN_TCanvas;
extern G__linked_taginfo G__GridCanvas_DictLN_TVirtualPad;
extern G__linked_taginfo G__GridCanvas_DictLN_TAttBBox2D;
extern G__linked_taginfo G__GridCanvas_DictLN_TPad;
extern G__linked_taginfo G__GridCanvas_DictLN_TLatex;
extern G__linked_taginfo G__GridCanvas_DictLN_TH1;
extern G__linked_taginfo G__GridCanvas_DictLN_GridCanvas;
extern G__linked_taginfo G__GridCanvas_DictLN_vectorlETPadmUcOallocatorlETPadmUgRsPgR;
extern G__linked_taginfo G__GridCanvas_DictLN_reverse_iteratorlEvectorlETPadmUcOallocatorlETPadmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GridCanvas_DictLN_GridCanvascLcLETitleAlignment;
extern G__linked_taginfo G__GridCanvas_DictLN_vectorlEvectorlETPadmUcOallocatorlETPadmUgRsPgRcOallocatorlEvectorlETPadmUcOallocatorlETPadmUgRsPgRsPgRsPgR;
extern G__linked_taginfo G__GridCanvas_DictLN_reverse_iteratorlEvectorlEvectorlETPadmUcOallocatorlETPadmUgRsPgRcOallocatorlEvectorlETPadmUcOallocatorlETPadmUgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
